apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}-svc
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 82
      targetPort: 82
      nodePort: {{ .Values.nodePort }}
      name: http
  selector:
    name: {{ template "app.name" . }}
